/**
 * Event namespace - bundles EventResource with event-related schemas
 */

// Re-export the resource class
export { EventResource } from '../client/resources/event.js'

// Re-export event schemas
export {
  HostSchema,
  EventSchema,
  GetEventParamsSchema,
  GetEventResponseSchema,
  GuestSchema,
  GetGuestParamsSchema,
  GetGuestResponseSchema,
  GetGuestsParamsSchema,
  GetGuestsResponseSchema,
  CreateEventRequestSchema,
  CreateEventResponseSchema,
  UpdateEventRequestSchema,
  UpdateEventResponseSchema,
  UpdateGuestStatusRequestSchema,
  UpdateGuestStatusResponseSchema,
  AddGuestInputSchema,
  AddGuestsRequestSchema,
  AddGuestsResponseSchema,
  SendInvitesRequestSchema,
  SendInvitesResponseSchema,
  AddHostRequestSchema,
  AddHostResponseSchema,
  CouponSchema,
  GetEventCouponsParamsSchema,
  GetEventCouponsResponseSchema,
  CreateEventCouponRequestSchema,
  CreateEventCouponResponseSchema,
  UpdateEventCouponRequestSchema,
  UpdateEventCouponResponseSchema,
  TicketTypeSchema,
  ListTicketTypesParamsSchema,
  ListTicketTypesResponseSchema,
  GetTicketTypeParamsSchema,
  GetTicketTypeResponseSchema,
  CreateTicketTypeRequestSchema,
  CreateTicketTypeResponseSchema,
  UpdateTicketTypeRequestSchema,
  UpdateTicketTypeResponseSchema,
  DeleteTicketTypeRequestSchema,
  DeleteTicketTypeResponseSchema,
} from '../schemas/event.js'

// Re-export event types
export type {
  Host,
  Event,
  GetEventParams,
  GetEventResponse,
  Guest,
  GetGuestParams,
  GetGuestResponse,
  GetGuestsParams,
  GetGuestsResponse,
  CreateEventRequest,
  CreateEventResponse,
  UpdateEventRequest,
  UpdateEventResponse,
  UpdateGuestStatusRequest,
  UpdateGuestStatusResponse,
  AddGuestInput,
  AddGuestsRequest,
  AddGuestsResponse,
  SendInvitesRequest,
  SendInvitesResponse,
  AddHostRequest,
  AddHostResponse,
  Coupon,
  GetEventCouponsParams,
  GetEventCouponsResponse,
  CreateEventCouponRequest,
  CreateEventCouponResponse,
  UpdateEventCouponRequest,
  UpdateEventCouponResponse,
  TicketType,
  ListTicketTypesParams,
  ListTicketTypesResponse,
  GetTicketTypeParams,
  GetTicketTypeResponse,
  CreateTicketTypeRequest,
  CreateTicketTypeResponse,
  UpdateTicketTypeRequest,
  UpdateTicketTypeResponse,
  DeleteTicketTypeRequest,
  DeleteTicketTypeResponse,
} from '../schemas/event.js'
